version: 
  '3.5'
services:
  gvsigonline:
    build: ./webapps/gvsig-online
    container_name:
      gvsig-online
    volumes:
      - ./webapps/gvsig-online:/srv/gvsig-online-deploy/gvsig-online
    #env_file:
    #  - ./secrets/.gvsigol
    entrypoint: ["/docker-entrypoint.sh"]
    restart: 
      on-failure

  nginx:
    build: ./docker-images/nginx
    container_name:
      nginx-gvsigol
    ports:
      - "8000:8000"
    volumes:
      - ./webapps/gvsig-online/gvsigol/assets:/srv/gvsig-online-deploy/gvsig-online/gvsigol/static
      - /var/www/media/srv/gvsig-online-deploy/gvsig-online/gvsigol/media
      - ./docker-images/nginx/sites-enabled/gvsigol.conf:/etc/nginx/conf.d/gvsigol.conf
    depends_on:
      - gvsigonline
    links:
      - gvsigonline
    restart: 
      on-failure



  postgresql_bd:
    build:
      ./docker-images/postgres/
    container_name:
      postgresql_bd
    #env_file: 
    #  ./secrets/.postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgresql_bd_data:/data/postgres
    ports:
      - "5432:5432"
    restart: 
      on-failure
  
volumes:
  postgresql_bd_data: