version: '3.5'
services:
  gvsigonline:
    build: ../gvsig-online
    container_name: gvsig-online
    env_file:
      - secrets/.env.postgres.example
#    depends_on:
#      - postgresql_bd
#    links:
#      - postgresql_bd
    ports:
      - 9000:9000
    restart:
      on-failure



  postgresql_bd:
    build: ./docker-images/postgres/
    container_name: postgresql_bd
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gvsigonline_v2
      PGDATA: /data/postgres
    volumes:
       - postgresql_bd_data:/data/postgres
    ports:
      - "5432:5432"
    restart:
      on-failure

volumes:
  postgresql_bd_data:
    driver: local